# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f6166e6ce7f9ce69ec133e1800dcf9db"
name = "AI SEO Assistant"
application_url = "https://ai-seo-assistant-8mqt.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://ai-seo-assistant-8mqt.onrender.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://ai-seo-assistant-8mqt.onrender.com/webhooks/app/scopes_update"

  # Mandatory compliance webhooks (customer privacy)
  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://ai-seo-assistant-8mqt.onrender.com/webhooks"

[access_scopes]
scopes = "read_products,write_products,read_content,write_content"

[auth]
redirect_urls = [ "https://ai-seo-assistant-8mqt.onrender.com/api/auth" ]